spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sa
    username: sa
    password: 
  h2: 
    console:
      enabled: true
    path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file: logs/account_mgt.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level: 
    com.bank.account.mgt.advice.BankAccountMgtAdvice: ERROR
    com.bank.account.mgt.service.impl: DEBUG
     
    
valid:
  commands: BALANCE,SEND,TOTAL,SENT
  patterns: SEND-[0-9]+-[A-Z]+, BALANCE, TOTAL-SENT-[A-Z-]+